language: python

services:
  - docker

install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t temp .

after_success:
  - docker tag temp:latest simonszu/dosage:latest
  - docker tag temp:latest simonszu/dosage:travis-$TRAVIS_BUILD_NUMBER
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push simonszu/dosage:latest
  - docker push simonszu/dosage:travis-$TRAVIS_BUILD_NUMBER
